# Generated by Django 6.0.6 on 2026-07-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['position', 'year', 'make', 'model']},
        ),
        migrations.AddField(
            model_name='car',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
